//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CollectorConfig{}, func(obj interface{}) { SetObjectDefaults_CollectorConfig(obj.(*CollectorConfig)) })
	return nil
}

func SetObjectDefaults_CollectorConfig(in *CollectorConfig) {
	if in.Spec.DefaultExporter.Protocol == "" {
		in.Spec.DefaultExporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
	}
	if in.Spec.DefaultExporter.TLS != nil {
		if in.Spec.DefaultExporter.TLS.InsecureSkipVerify == nil {
			var ptrVar1 bool = false
			in.Spec.DefaultExporter.TLS.InsecureSkipVerify = &ptrVar1
		}
		if in.Spec.DefaultExporter.TLS.ReloadInterval == 0 {
			in.Spec.DefaultExporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
		}
	}
	if in.Spec.DefaultExporter.Timeout == 0 {
		in.Spec.DefaultExporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
	}
	if in.Spec.DefaultExporter.ReadBufferSize == 0 {
		in.Spec.DefaultExporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
	}
	if in.Spec.DefaultExporter.WriteBufferSize == 0 {
		in.Spec.DefaultExporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
	}
	if in.Spec.DefaultExporter.Encoding == "" {
		in.Spec.DefaultExporter.Encoding = MessageEncoding(MessageEncodingProto)
	}
	if in.Spec.DefaultExporter.RetryOnFailure.Enabled == nil {
		var ptrVar1 bool = true
		in.Spec.DefaultExporter.RetryOnFailure.Enabled = &ptrVar1
	}
	if in.Spec.DefaultExporter.RetryOnFailure.InitialInterval == 0 {
		in.Spec.DefaultExporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
	}
	if in.Spec.DefaultExporter.RetryOnFailure.MaxInterval == 0 {
		in.Spec.DefaultExporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
	}
	if in.Spec.DefaultExporter.RetryOnFailure.MaxElapsedTime == 0 {
		in.Spec.DefaultExporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
	}
	if in.Spec.DefaultExporter.RetryOnFailure.Multiplier == 0 {
		in.Spec.DefaultExporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
	}
	if in.Spec.DefaultExporter.Compression == "" {
		in.Spec.DefaultExporter.Compression = Compression(CompressionGzip)
	}
	if in.Spec.DefaultExporter.Verbosity == "" {
		in.Spec.DefaultExporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
	}
	if in.Spec.Signals.Metrics.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Signals.Metrics.Enabled = &ptrVar1
	}
	for i := range in.Spec.Signals.Metrics.Targets {
		a := &in.Spec.Signals.Metrics.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Signals.Logs.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Signals.Logs.Enabled = &ptrVar1
	}
	for i := range in.Spec.Signals.Logs.Targets {
		a := &in.Spec.Signals.Logs.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Signals.Traces.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Signals.Traces.Enabled = &ptrVar1
	}
	for i := range in.Spec.Signals.Traces.Targets {
		a := &in.Spec.Signals.Traces.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Signals.Profiles.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Signals.Profiles.Enabled = &ptrVar1
	}
	for i := range in.Spec.Signals.Profiles.Targets {
		a := &in.Spec.Signals.Profiles.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Signals.Events.Enabled == nil {
		var ptrVar1 bool = false
		in.Spec.Signals.Events.Enabled = &ptrVar1
	}
	for i := range in.Spec.Signals.Events.Targets {
		a := &in.Spec.Signals.Events.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Logs.Level == "" {
		in.Spec.Logs.Level = LogLevel(LogLevelInfo)
	}
	if in.Spec.Logs.Encoding == "" {
		in.Spec.Logs.Encoding = LogEncoding(LogEncodingConsole)
	}
	if in.Spec.Metrics.Level == "" {
		in.Spec.Metrics.Level = MetricsVerbosityLevel(MetricsVerbosityLevelNormal)
	}
}
