//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CollectorConfig{}, func(obj interface{}) { SetObjectDefaults_CollectorConfig(obj.(*CollectorConfig)) })
	return nil
}

func SetObjectDefaults_CollectorConfig(in *CollectorConfig) {
	for i := range in.Spec.Targets {
		a := &in.Spec.Targets[i]
		if a.Exporter.OTLPGRPCExporter != nil {
			if a.Exporter.OTLPGRPCExporter.TLS != nil {
				if a.Exporter.OTLPGRPCExporter.TLS.InsecureSkipVerify == nil {
					var ptrVar1 bool = false
					a.Exporter.OTLPGRPCExporter.TLS.InsecureSkipVerify = &ptrVar1
				}
				if a.Exporter.OTLPGRPCExporter.TLS.ReloadInterval == 0 {
					a.Exporter.OTLPGRPCExporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
				}
			}
			if a.Exporter.OTLPGRPCExporter.Timeout == 0 {
				a.Exporter.OTLPGRPCExporter.Timeout = time.Duration(DefaultGRPCExporterClientTimeout)
			}
			if a.Exporter.OTLPGRPCExporter.ReadBufferSize == 0 {
				a.Exporter.OTLPGRPCExporter.ReadBufferSize = int(DefaultGRPCExporterClientReadBufferSize)
			}
			if a.Exporter.OTLPGRPCExporter.WriteBufferSize == 0 {
				a.Exporter.OTLPGRPCExporter.WriteBufferSize = int(DefaultGRPCExporterClientWriteBufferSize)
			}
			if a.Exporter.OTLPGRPCExporter.RetryOnFailure.Enabled == nil {
				var ptrVar1 bool = true
				a.Exporter.OTLPGRPCExporter.RetryOnFailure.Enabled = &ptrVar1
			}
			if a.Exporter.OTLPGRPCExporter.RetryOnFailure.InitialInterval == 0 {
				a.Exporter.OTLPGRPCExporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
			}
			if a.Exporter.OTLPGRPCExporter.RetryOnFailure.MaxInterval == 0 {
				a.Exporter.OTLPGRPCExporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
			}
			if a.Exporter.OTLPGRPCExporter.RetryOnFailure.MaxElapsedTime == 0 {
				a.Exporter.OTLPGRPCExporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
			}
			if a.Exporter.OTLPGRPCExporter.RetryOnFailure.Multiplier == 0 {
				a.Exporter.OTLPGRPCExporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
			}
			if a.Exporter.OTLPGRPCExporter.Compression == "" {
				a.Exporter.OTLPGRPCExporter.Compression = Compression(CompressionGzip)
			}
		}
		if a.Exporter.OTLPHTTPExporter != nil {
			if a.Exporter.OTLPHTTPExporter.TLS != nil {
				if a.Exporter.OTLPHTTPExporter.TLS.InsecureSkipVerify == nil {
					var ptrVar1 bool = false
					a.Exporter.OTLPHTTPExporter.TLS.InsecureSkipVerify = &ptrVar1
				}
				if a.Exporter.OTLPHTTPExporter.TLS.ReloadInterval == 0 {
					a.Exporter.OTLPHTTPExporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
				}
			}
			if a.Exporter.OTLPHTTPExporter.Timeout == 0 {
				a.Exporter.OTLPHTTPExporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
			}
			if a.Exporter.OTLPHTTPExporter.ReadBufferSize == 0 {
				a.Exporter.OTLPHTTPExporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
			}
			if a.Exporter.OTLPHTTPExporter.WriteBufferSize == 0 {
				a.Exporter.OTLPHTTPExporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
			}
			if a.Exporter.OTLPHTTPExporter.Encoding == "" {
				a.Exporter.OTLPHTTPExporter.Encoding = MessageEncoding(MessageEncodingProto)
			}
			if a.Exporter.OTLPHTTPExporter.RetryOnFailure.Enabled == nil {
				var ptrVar1 bool = true
				a.Exporter.OTLPHTTPExporter.RetryOnFailure.Enabled = &ptrVar1
			}
			if a.Exporter.OTLPHTTPExporter.RetryOnFailure.InitialInterval == 0 {
				a.Exporter.OTLPHTTPExporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
			}
			if a.Exporter.OTLPHTTPExporter.RetryOnFailure.MaxInterval == 0 {
				a.Exporter.OTLPHTTPExporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
			}
			if a.Exporter.OTLPHTTPExporter.RetryOnFailure.MaxElapsedTime == 0 {
				a.Exporter.OTLPHTTPExporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
			}
			if a.Exporter.OTLPHTTPExporter.RetryOnFailure.Multiplier == 0 {
				a.Exporter.OTLPHTTPExporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
			}
			if a.Exporter.OTLPHTTPExporter.Compression == "" {
				a.Exporter.OTLPHTTPExporter.Compression = Compression(CompressionGzip)
			}
		}
		if a.Exporter.DebugExporter != nil {
			if a.Exporter.DebugExporter.Verbosity == "" {
				a.Exporter.DebugExporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
			}
		}
	}
	if in.Spec.Logs.Level == "" {
		in.Spec.Logs.Level = LogLevel(LogLevelInfo)
	}
	if in.Spec.Logs.Encoding == "" {
		in.Spec.Logs.Encoding = LogEncoding(LogEncodingConsole)
	}
	if in.Spec.Metrics.Level == "" {
		in.Spec.Metrics.Level = MetricsVerbosityLevel(MetricsVerbosityLevelNormal)
	}
}
