//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CollectorConfig{}, func(obj interface{}) { SetObjectDefaults_CollectorConfig(obj.(*CollectorConfig)) })
	return nil
}

func SetObjectDefaults_CollectorConfig(in *CollectorConfig) {
	for i := range in.Spec.Targets {
		a := &in.Spec.Targets[i]
		if a.Exporter.Protocol == "" {
			a.Exporter.Protocol = ExporterProtocol(ExporterProtocolHTTP)
		}
		if a.Exporter.TLS != nil {
			if a.Exporter.TLS.InsecureSkipVerify == nil {
				var ptrVar1 bool = false
				a.Exporter.TLS.InsecureSkipVerify = &ptrVar1
			}
			if a.Exporter.TLS.ReloadInterval == 0 {
				a.Exporter.TLS.ReloadInterval = time.Duration(DefaultTLSReloadInterval)
			}
		}
		if a.Exporter.Timeout == 0 {
			a.Exporter.Timeout = time.Duration(DefaultHTTPExporterClientTimeout)
		}
		if a.Exporter.ReadBufferSize == 0 {
			a.Exporter.ReadBufferSize = int(DefaultHTTPExporterClientReadBufferSize)
		}
		if a.Exporter.WriteBufferSize == 0 {
			a.Exporter.WriteBufferSize = int(DefaultHTTPExporterClientWriteBufferSize)
		}
		if a.Exporter.Encoding == "" {
			a.Exporter.Encoding = MessageEncoding(MessageEncodingProto)
		}
		if a.Exporter.RetryOnFailure.Enabled == nil {
			var ptrVar1 bool = true
			a.Exporter.RetryOnFailure.Enabled = &ptrVar1
		}
		if a.Exporter.RetryOnFailure.InitialInterval == 0 {
			a.Exporter.RetryOnFailure.InitialInterval = time.Duration(DefaultRetryInitialInterval)
		}
		if a.Exporter.RetryOnFailure.MaxInterval == 0 {
			a.Exporter.RetryOnFailure.MaxInterval = time.Duration(DefaultRetryMaxInterval)
		}
		if a.Exporter.RetryOnFailure.MaxElapsedTime == 0 {
			a.Exporter.RetryOnFailure.MaxElapsedTime = time.Duration(DefaultRetryMaxElapsedTime)
		}
		if a.Exporter.RetryOnFailure.Multiplier == 0 {
			a.Exporter.RetryOnFailure.Multiplier = float64(DefaultRetryMultiplier)
		}
		if a.Exporter.Compression == "" {
			a.Exporter.Compression = Compression(CompressionGzip)
		}
		if a.Exporter.Verbosity == "" {
			a.Exporter.Verbosity = DebugExporterVerbosity(DebugExporterVerbosityBasic)
		}
	}
	if in.Spec.Logs.Level == "" {
		in.Spec.Logs.Level = LogLevel(LogLevelInfo)
	}
	if in.Spec.Logs.Encoding == "" {
		in.Spec.Logs.Encoding = LogEncoding(LogEncodingConsole)
	}
	if in.Spec.Metrics.Level == "" {
		in.Spec.Metrics.Level = MetricsVerbosityLevel(MetricsVerbosityLevelNormal)
	}
}
