//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-otelcol/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CollectorConfig)(nil), (*config.CollectorConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig(a.(*CollectorConfig), b.(*config.CollectorConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorConfig)(nil), (*CollectorConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig(a.(*config.CollectorConfig), b.(*CollectorConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorConfigSpec)(nil), (*config.CollectorConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(a.(*CollectorConfigSpec), b.(*config.CollectorConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorConfigSpec)(nil), (*CollectorConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(a.(*config.CollectorConfigSpec), b.(*CollectorConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorLogsConfig)(nil), (*config.CollectorLogsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(a.(*CollectorLogsConfig), b.(*config.CollectorLogsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorLogsConfig)(nil), (*CollectorLogsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(a.(*config.CollectorLogsConfig), b.(*CollectorLogsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CollectorMetricsConfig)(nil), (*config.CollectorMetricsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig(a.(*CollectorMetricsConfig), b.(*config.CollectorMetricsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CollectorMetricsConfig)(nil), (*CollectorMetricsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig(a.(*config.CollectorMetricsConfig), b.(*CollectorMetricsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContextConditions)(nil), (*config.ContextConditions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContextConditions_To_config_ContextConditions(a.(*ContextConditions), b.(*config.ContextConditions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ContextConditions)(nil), (*ContextConditions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ContextConditions_To_v1alpha1_ContextConditions(a.(*config.ContextConditions), b.(*ContextConditions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExporterConfig)(nil), (*config.ExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExporterConfig_To_config_ExporterConfig(a.(*ExporterConfig), b.(*config.ExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ExporterConfig)(nil), (*ExporterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ExporterConfig_To_v1alpha1_ExporterConfig(a.(*config.ExporterConfig), b.(*ExporterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FilterAttribute)(nil), (*config.FilterAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FilterAttribute_To_config_FilterAttribute(a.(*FilterAttribute), b.(*config.FilterAttribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FilterAttribute)(nil), (*FilterAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FilterAttribute_To_v1alpha1_FilterAttribute(a.(*config.FilterAttribute), b.(*FilterAttribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FilterRule)(nil), (*config.FilterRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FilterRule_To_config_FilterRule(a.(*FilterRule), b.(*config.FilterRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FilterRule)(nil), (*FilterRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FilterRule_To_v1alpha1_FilterRule(a.(*config.FilterRule), b.(*FilterRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogFilters)(nil), (*config.LogFilters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogFilters_To_config_LogFilters(a.(*LogFilters), b.(*config.LogFilters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LogFilters)(nil), (*LogFilters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LogFilters_To_v1alpha1_LogFilters(a.(*config.LogFilters), b.(*LogFilters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogMatchProperties)(nil), (*config.LogMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogMatchProperties_To_config_LogMatchProperties(a.(*LogMatchProperties), b.(*config.LogMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LogMatchProperties)(nil), (*LogMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LogMatchProperties_To_v1alpha1_LogMatchProperties(a.(*config.LogMatchProperties), b.(*LogMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogSeverityNumberMatchProperties)(nil), (*config.LogSeverityNumberMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogSeverityNumberMatchProperties_To_config_LogSeverityNumberMatchProperties(a.(*LogSeverityNumberMatchProperties), b.(*config.LogSeverityNumberMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LogSeverityNumberMatchProperties)(nil), (*LogSeverityNumberMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LogSeverityNumberMatchProperties_To_v1alpha1_LogSeverityNumberMatchProperties(a.(*config.LogSeverityNumberMatchProperties), b.(*LogSeverityNumberMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricFilters)(nil), (*config.MetricFilters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricFilters_To_config_MetricFilters(a.(*MetricFilters), b.(*config.MetricFilters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MetricFilters)(nil), (*MetricFilters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MetricFilters_To_v1alpha1_MetricFilters(a.(*config.MetricFilters), b.(*MetricFilters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricMatchProperties)(nil), (*config.MetricMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricMatchProperties_To_config_MetricMatchProperties(a.(*MetricMatchProperties), b.(*config.MetricMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MetricMatchProperties)(nil), (*MetricMatchProperties)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MetricMatchProperties_To_v1alpha1_MetricMatchProperties(a.(*config.MetricMatchProperties), b.(*MetricMatchProperties), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegexpConfig)(nil), (*config.RegexpConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegexpConfig_To_config_RegexpConfig(a.(*RegexpConfig), b.(*config.RegexpConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RegexpConfig)(nil), (*RegexpConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RegexpConfig_To_v1alpha1_RegexpConfig(a.(*config.RegexpConfig), b.(*RegexpConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceReference)(nil), (*config.ResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceReference_To_config_ResourceReference(a.(*ResourceReference), b.(*config.ResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ResourceReference)(nil), (*ResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ResourceReference_To_v1alpha1_ResourceReference(a.(*config.ResourceReference), b.(*ResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceReferenceDetails)(nil), (*config.ResourceReferenceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(a.(*ResourceReferenceDetails), b.(*config.ResourceReferenceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ResourceReferenceDetails)(nil), (*ResourceReferenceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(a.(*config.ResourceReferenceDetails), b.(*ResourceReferenceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RetryOnFailureConfig)(nil), (*config.RetryOnFailureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(a.(*RetryOnFailureConfig), b.(*config.RetryOnFailureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RetryOnFailureConfig)(nil), (*RetryOnFailureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(a.(*config.RetryOnFailureConfig), b.(*RetryOnFailureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SignalConfig)(nil), (*config.SignalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SignalConfig_To_config_SignalConfig(a.(*SignalConfig), b.(*config.SignalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SignalConfig)(nil), (*SignalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SignalConfig_To_v1alpha1_SignalConfig(a.(*config.SignalConfig), b.(*SignalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SignalTarget)(nil), (*config.SignalTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SignalTarget_To_config_SignalTarget(a.(*SignalTarget), b.(*config.SignalTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SignalTarget)(nil), (*SignalTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SignalTarget_To_v1alpha1_SignalTarget(a.(*config.SignalTarget), b.(*SignalTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SignalsConfig)(nil), (*config.SignalsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SignalsConfig_To_config_SignalsConfig(a.(*SignalsConfig), b.(*config.SignalsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SignalsConfig)(nil), (*SignalsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SignalsConfig_To_v1alpha1_SignalsConfig(a.(*config.SignalsConfig), b.(*SignalsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSConfig)(nil), (*config.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSConfig_To_config_TLSConfig(a.(*TLSConfig), b.(*config.TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TLSConfig)(nil), (*TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TLSConfig_To_v1alpha1_TLSConfig(a.(*config.TLSConfig), b.(*TLSConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in *CollectorConfig, out *config.CollectorConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in *CollectorConfig, out *config.CollectorConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorConfig_To_config_CollectorConfig(in, out, s)
}

func autoConvert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in *config.CollectorConfig, out *CollectorConfig, s conversion.Scope) error {
	if err := Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig is an autogenerated conversion function.
func Convert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in *config.CollectorConfig, out *CollectorConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorConfig_To_v1alpha1_CollectorConfig(in, out, s)
}

func autoConvert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in *CollectorConfigSpec, out *config.CollectorConfigSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_SignalsConfig_To_config_SignalsConfig(&in.Signals, &out.Signals, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig(&in.Metrics, &out.Metrics, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in *CollectorConfigSpec, out *config.CollectorConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorConfigSpec_To_config_CollectorConfigSpec(in, out, s)
}

func autoConvert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in *config.CollectorConfigSpec, out *CollectorConfigSpec, s conversion.Scope) error {
	if err := Convert_config_SignalsConfig_To_v1alpha1_SignalsConfig(&in.Signals, &out.Signals, s); err != nil {
		return err
	}
	if err := Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	if err := Convert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig(&in.Metrics, &out.Metrics, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec is an autogenerated conversion function.
func Convert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in *config.CollectorConfigSpec, out *CollectorConfigSpec, s conversion.Scope) error {
	return autoConvert_config_CollectorConfigSpec_To_v1alpha1_CollectorConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in *CollectorLogsConfig, out *config.CollectorLogsConfig, s conversion.Scope) error {
	out.Level = config.LogLevel(in.Level)
	out.Encoding = config.LogEncoding(in.Encoding)
	return nil
}

// Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in *CollectorLogsConfig, out *config.CollectorLogsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorLogsConfig_To_config_CollectorLogsConfig(in, out, s)
}

func autoConvert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in *config.CollectorLogsConfig, out *CollectorLogsConfig, s conversion.Scope) error {
	out.Level = LogLevel(in.Level)
	out.Encoding = LogEncoding(in.Encoding)
	return nil
}

// Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig is an autogenerated conversion function.
func Convert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in *config.CollectorLogsConfig, out *CollectorLogsConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorLogsConfig_To_v1alpha1_CollectorLogsConfig(in, out, s)
}

func autoConvert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig(in *CollectorMetricsConfig, out *config.CollectorMetricsConfig, s conversion.Scope) error {
	out.Level = config.MetricsVerbosityLevel(in.Level)
	return nil
}

// Convert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig is an autogenerated conversion function.
func Convert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig(in *CollectorMetricsConfig, out *config.CollectorMetricsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CollectorMetricsConfig_To_config_CollectorMetricsConfig(in, out, s)
}

func autoConvert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig(in *config.CollectorMetricsConfig, out *CollectorMetricsConfig, s conversion.Scope) error {
	out.Level = MetricsVerbosityLevel(in.Level)
	return nil
}

// Convert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig is an autogenerated conversion function.
func Convert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig(in *config.CollectorMetricsConfig, out *CollectorMetricsConfig, s conversion.Scope) error {
	return autoConvert_config_CollectorMetricsConfig_To_v1alpha1_CollectorMetricsConfig(in, out, s)
}

func autoConvert_v1alpha1_ContextConditions_To_config_ContextConditions(in *ContextConditions, out *config.ContextConditions, s conversion.Scope) error {
	out.Context = in.Context
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	out.ErrorMode = config.FilterErrorMode(in.ErrorMode)
	return nil
}

// Convert_v1alpha1_ContextConditions_To_config_ContextConditions is an autogenerated conversion function.
func Convert_v1alpha1_ContextConditions_To_config_ContextConditions(in *ContextConditions, out *config.ContextConditions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContextConditions_To_config_ContextConditions(in, out, s)
}

func autoConvert_config_ContextConditions_To_v1alpha1_ContextConditions(in *config.ContextConditions, out *ContextConditions, s conversion.Scope) error {
	out.Context = in.Context
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	out.ErrorMode = FilterErrorMode(in.ErrorMode)
	return nil
}

// Convert_config_ContextConditions_To_v1alpha1_ContextConditions is an autogenerated conversion function.
func Convert_config_ContextConditions_To_v1alpha1_ContextConditions(in *config.ContextConditions, out *ContextConditions, s conversion.Scope) error {
	return autoConvert_config_ContextConditions_To_v1alpha1_ContextConditions(in, out, s)
}

func autoConvert_v1alpha1_ExporterConfig_To_config_ExporterConfig(in *ExporterConfig, out *config.ExporterConfig, s conversion.Scope) error {
	out.Protocol = config.ExporterProtocol(in.Protocol)
	out.Endpoint = in.Endpoint
	out.TLS = (*config.TLSConfig)(unsafe.Pointer(in.TLS))
	out.Token = (*config.ResourceReference)(unsafe.Pointer(in.Token))
	out.Timeout = time.Duration(in.Timeout)
	out.ReadBufferSize = in.ReadBufferSize
	out.WriteBufferSize = in.WriteBufferSize
	out.Encoding = config.MessageEncoding(in.Encoding)
	if err := Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(&in.RetryOnFailure, &out.RetryOnFailure, s); err != nil {
		return err
	}
	out.Compression = config.Compression(in.Compression)
	out.Verbosity = config.DebugExporterVerbosity(in.Verbosity)
	return nil
}

// Convert_v1alpha1_ExporterConfig_To_config_ExporterConfig is an autogenerated conversion function.
func Convert_v1alpha1_ExporterConfig_To_config_ExporterConfig(in *ExporterConfig, out *config.ExporterConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExporterConfig_To_config_ExporterConfig(in, out, s)
}

func autoConvert_config_ExporterConfig_To_v1alpha1_ExporterConfig(in *config.ExporterConfig, out *ExporterConfig, s conversion.Scope) error {
	out.Protocol = ExporterProtocol(in.Protocol)
	out.Endpoint = in.Endpoint
	out.TLS = (*TLSConfig)(unsafe.Pointer(in.TLS))
	out.Token = (*ResourceReference)(unsafe.Pointer(in.Token))
	out.Timeout = time.Duration(in.Timeout)
	out.ReadBufferSize = in.ReadBufferSize
	out.WriteBufferSize = in.WriteBufferSize
	out.Encoding = MessageEncoding(in.Encoding)
	if err := Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(&in.RetryOnFailure, &out.RetryOnFailure, s); err != nil {
		return err
	}
	out.Compression = Compression(in.Compression)
	out.Verbosity = DebugExporterVerbosity(in.Verbosity)
	return nil
}

// Convert_config_ExporterConfig_To_v1alpha1_ExporterConfig is an autogenerated conversion function.
func Convert_config_ExporterConfig_To_v1alpha1_ExporterConfig(in *config.ExporterConfig, out *ExporterConfig, s conversion.Scope) error {
	return autoConvert_config_ExporterConfig_To_v1alpha1_ExporterConfig(in, out, s)
}

func autoConvert_v1alpha1_FilterAttribute_To_config_FilterAttribute(in *FilterAttribute, out *config.FilterAttribute, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_FilterAttribute_To_config_FilterAttribute is an autogenerated conversion function.
func Convert_v1alpha1_FilterAttribute_To_config_FilterAttribute(in *FilterAttribute, out *config.FilterAttribute, s conversion.Scope) error {
	return autoConvert_v1alpha1_FilterAttribute_To_config_FilterAttribute(in, out, s)
}

func autoConvert_config_FilterAttribute_To_v1alpha1_FilterAttribute(in *config.FilterAttribute, out *FilterAttribute, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_config_FilterAttribute_To_v1alpha1_FilterAttribute is an autogenerated conversion function.
func Convert_config_FilterAttribute_To_v1alpha1_FilterAttribute(in *config.FilterAttribute, out *FilterAttribute, s conversion.Scope) error {
	return autoConvert_config_FilterAttribute_To_v1alpha1_FilterAttribute(in, out, s)
}

func autoConvert_v1alpha1_FilterRule_To_config_FilterRule(in *FilterRule, out *config.FilterRule, s conversion.Scope) error {
	out.ErrorMode = config.FilterErrorMode(in.ErrorMode)
	out.Metrics = (*config.MetricFilters)(unsafe.Pointer(in.Metrics))
	out.Logs = (*config.LogFilters)(unsafe.Pointer(in.Logs))
	out.MetricConditions = *(*[]config.ContextConditions)(unsafe.Pointer(&in.MetricConditions))
	out.LogConditions = *(*[]config.ContextConditions)(unsafe.Pointer(&in.LogConditions))
	out.Conditions = *(*[]config.ContextConditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_FilterRule_To_config_FilterRule is an autogenerated conversion function.
func Convert_v1alpha1_FilterRule_To_config_FilterRule(in *FilterRule, out *config.FilterRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_FilterRule_To_config_FilterRule(in, out, s)
}

func autoConvert_config_FilterRule_To_v1alpha1_FilterRule(in *config.FilterRule, out *FilterRule, s conversion.Scope) error {
	out.ErrorMode = FilterErrorMode(in.ErrorMode)
	out.Metrics = (*MetricFilters)(unsafe.Pointer(in.Metrics))
	out.Logs = (*LogFilters)(unsafe.Pointer(in.Logs))
	out.MetricConditions = *(*[]ContextConditions)(unsafe.Pointer(&in.MetricConditions))
	out.LogConditions = *(*[]ContextConditions)(unsafe.Pointer(&in.LogConditions))
	out.Conditions = *(*[]ContextConditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_config_FilterRule_To_v1alpha1_FilterRule is an autogenerated conversion function.
func Convert_config_FilterRule_To_v1alpha1_FilterRule(in *config.FilterRule, out *FilterRule, s conversion.Scope) error {
	return autoConvert_config_FilterRule_To_v1alpha1_FilterRule(in, out, s)
}

func autoConvert_v1alpha1_LogFilters_To_config_LogFilters(in *LogFilters, out *config.LogFilters, s conversion.Scope) error {
	out.Include = (*config.LogMatchProperties)(unsafe.Pointer(in.Include))
	out.Exclude = (*config.LogMatchProperties)(unsafe.Pointer(in.Exclude))
	out.Resource = *(*[]string)(unsafe.Pointer(&in.Resource))
	out.LogRecord = *(*[]string)(unsafe.Pointer(&in.LogRecord))
	return nil
}

// Convert_v1alpha1_LogFilters_To_config_LogFilters is an autogenerated conversion function.
func Convert_v1alpha1_LogFilters_To_config_LogFilters(in *LogFilters, out *config.LogFilters, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogFilters_To_config_LogFilters(in, out, s)
}

func autoConvert_config_LogFilters_To_v1alpha1_LogFilters(in *config.LogFilters, out *LogFilters, s conversion.Scope) error {
	out.Include = (*LogMatchProperties)(unsafe.Pointer(in.Include))
	out.Exclude = (*LogMatchProperties)(unsafe.Pointer(in.Exclude))
	out.Resource = *(*[]string)(unsafe.Pointer(&in.Resource))
	out.LogRecord = *(*[]string)(unsafe.Pointer(&in.LogRecord))
	return nil
}

// Convert_config_LogFilters_To_v1alpha1_LogFilters is an autogenerated conversion function.
func Convert_config_LogFilters_To_v1alpha1_LogFilters(in *config.LogFilters, out *LogFilters, s conversion.Scope) error {
	return autoConvert_config_LogFilters_To_v1alpha1_LogFilters(in, out, s)
}

func autoConvert_v1alpha1_LogMatchProperties_To_config_LogMatchProperties(in *LogMatchProperties, out *config.LogMatchProperties, s conversion.Scope) error {
	out.MatchType = config.MatchType(in.MatchType)
	out.ResourceAttributes = *(*[]config.FilterAttribute)(unsafe.Pointer(&in.ResourceAttributes))
	out.RecordAttributes = *(*[]config.FilterAttribute)(unsafe.Pointer(&in.RecordAttributes))
	out.SeverityTexts = *(*[]string)(unsafe.Pointer(&in.SeverityTexts))
	out.SeverityNumber = (*config.LogSeverityNumberMatchProperties)(unsafe.Pointer(in.SeverityNumber))
	out.Bodies = *(*[]string)(unsafe.Pointer(&in.Bodies))
	return nil
}

// Convert_v1alpha1_LogMatchProperties_To_config_LogMatchProperties is an autogenerated conversion function.
func Convert_v1alpha1_LogMatchProperties_To_config_LogMatchProperties(in *LogMatchProperties, out *config.LogMatchProperties, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogMatchProperties_To_config_LogMatchProperties(in, out, s)
}

func autoConvert_config_LogMatchProperties_To_v1alpha1_LogMatchProperties(in *config.LogMatchProperties, out *LogMatchProperties, s conversion.Scope) error {
	out.MatchType = FilterMatchType(in.MatchType)
	out.ResourceAttributes = *(*[]FilterAttribute)(unsafe.Pointer(&in.ResourceAttributes))
	out.RecordAttributes = *(*[]FilterAttribute)(unsafe.Pointer(&in.RecordAttributes))
	out.SeverityTexts = *(*[]string)(unsafe.Pointer(&in.SeverityTexts))
	out.SeverityNumber = (*LogSeverityNumberMatchProperties)(unsafe.Pointer(in.SeverityNumber))
	out.Bodies = *(*[]string)(unsafe.Pointer(&in.Bodies))
	return nil
}

// Convert_config_LogMatchProperties_To_v1alpha1_LogMatchProperties is an autogenerated conversion function.
func Convert_config_LogMatchProperties_To_v1alpha1_LogMatchProperties(in *config.LogMatchProperties, out *LogMatchProperties, s conversion.Scope) error {
	return autoConvert_config_LogMatchProperties_To_v1alpha1_LogMatchProperties(in, out, s)
}

func autoConvert_v1alpha1_LogSeverityNumberMatchProperties_To_config_LogSeverityNumberMatchProperties(in *LogSeverityNumberMatchProperties, out *config.LogSeverityNumberMatchProperties, s conversion.Scope) error {
	out.Min = in.Min
	out.MatchUndefined = (*bool)(unsafe.Pointer(in.MatchUndefined))
	return nil
}

// Convert_v1alpha1_LogSeverityNumberMatchProperties_To_config_LogSeverityNumberMatchProperties is an autogenerated conversion function.
func Convert_v1alpha1_LogSeverityNumberMatchProperties_To_config_LogSeverityNumberMatchProperties(in *LogSeverityNumberMatchProperties, out *config.LogSeverityNumberMatchProperties, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogSeverityNumberMatchProperties_To_config_LogSeverityNumberMatchProperties(in, out, s)
}

func autoConvert_config_LogSeverityNumberMatchProperties_To_v1alpha1_LogSeverityNumberMatchProperties(in *config.LogSeverityNumberMatchProperties, out *LogSeverityNumberMatchProperties, s conversion.Scope) error {
	out.Min = in.Min
	out.MatchUndefined = (*bool)(unsafe.Pointer(in.MatchUndefined))
	return nil
}

// Convert_config_LogSeverityNumberMatchProperties_To_v1alpha1_LogSeverityNumberMatchProperties is an autogenerated conversion function.
func Convert_config_LogSeverityNumberMatchProperties_To_v1alpha1_LogSeverityNumberMatchProperties(in *config.LogSeverityNumberMatchProperties, out *LogSeverityNumberMatchProperties, s conversion.Scope) error {
	return autoConvert_config_LogSeverityNumberMatchProperties_To_v1alpha1_LogSeverityNumberMatchProperties(in, out, s)
}

func autoConvert_v1alpha1_MetricFilters_To_config_MetricFilters(in *MetricFilters, out *config.MetricFilters, s conversion.Scope) error {
	out.Include = (*config.MetricMatchProperties)(unsafe.Pointer(in.Include))
	out.Exclude = (*config.MetricMatchProperties)(unsafe.Pointer(in.Exclude))
	out.Resource = *(*[]string)(unsafe.Pointer(&in.Resource))
	out.Metric = *(*[]string)(unsafe.Pointer(&in.Metric))
	out.DataPoint = *(*[]string)(unsafe.Pointer(&in.DataPoint))
	return nil
}

// Convert_v1alpha1_MetricFilters_To_config_MetricFilters is an autogenerated conversion function.
func Convert_v1alpha1_MetricFilters_To_config_MetricFilters(in *MetricFilters, out *config.MetricFilters, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricFilters_To_config_MetricFilters(in, out, s)
}

func autoConvert_config_MetricFilters_To_v1alpha1_MetricFilters(in *config.MetricFilters, out *MetricFilters, s conversion.Scope) error {
	out.Include = (*MetricMatchProperties)(unsafe.Pointer(in.Include))
	out.Exclude = (*MetricMatchProperties)(unsafe.Pointer(in.Exclude))
	out.Resource = *(*[]string)(unsafe.Pointer(&in.Resource))
	out.Metric = *(*[]string)(unsafe.Pointer(&in.Metric))
	out.DataPoint = *(*[]string)(unsafe.Pointer(&in.DataPoint))
	return nil
}

// Convert_config_MetricFilters_To_v1alpha1_MetricFilters is an autogenerated conversion function.
func Convert_config_MetricFilters_To_v1alpha1_MetricFilters(in *config.MetricFilters, out *MetricFilters, s conversion.Scope) error {
	return autoConvert_config_MetricFilters_To_v1alpha1_MetricFilters(in, out, s)
}

func autoConvert_v1alpha1_MetricMatchProperties_To_config_MetricMatchProperties(in *MetricMatchProperties, out *config.MetricMatchProperties, s conversion.Scope) error {
	out.MatchType = config.MatchType(in.MatchType)
	out.Regexp = (*config.RegexpConfig)(unsafe.Pointer(in.Regexp))
	out.MetricNames = *(*[]string)(unsafe.Pointer(&in.MetricNames))
	out.Expressions = *(*[]string)(unsafe.Pointer(&in.Expressions))
	out.ResourceAttributes = *(*[]config.FilterAttribute)(unsafe.Pointer(&in.ResourceAttributes))
	return nil
}

// Convert_v1alpha1_MetricMatchProperties_To_config_MetricMatchProperties is an autogenerated conversion function.
func Convert_v1alpha1_MetricMatchProperties_To_config_MetricMatchProperties(in *MetricMatchProperties, out *config.MetricMatchProperties, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricMatchProperties_To_config_MetricMatchProperties(in, out, s)
}

func autoConvert_config_MetricMatchProperties_To_v1alpha1_MetricMatchProperties(in *config.MetricMatchProperties, out *MetricMatchProperties, s conversion.Scope) error {
	out.MatchType = FilterMatchType(in.MatchType)
	out.Regexp = (*RegexpConfig)(unsafe.Pointer(in.Regexp))
	out.MetricNames = *(*[]string)(unsafe.Pointer(&in.MetricNames))
	out.Expressions = *(*[]string)(unsafe.Pointer(&in.Expressions))
	out.ResourceAttributes = *(*[]FilterAttribute)(unsafe.Pointer(&in.ResourceAttributes))
	return nil
}

// Convert_config_MetricMatchProperties_To_v1alpha1_MetricMatchProperties is an autogenerated conversion function.
func Convert_config_MetricMatchProperties_To_v1alpha1_MetricMatchProperties(in *config.MetricMatchProperties, out *MetricMatchProperties, s conversion.Scope) error {
	return autoConvert_config_MetricMatchProperties_To_v1alpha1_MetricMatchProperties(in, out, s)
}

func autoConvert_v1alpha1_RegexpConfig_To_config_RegexpConfig(in *RegexpConfig, out *config.RegexpConfig, s conversion.Scope) error {
	out.CacheEnabled = (*bool)(unsafe.Pointer(in.CacheEnabled))
	out.CacheMaxNumEntries = in.CacheMaxNumEntries
	return nil
}

// Convert_v1alpha1_RegexpConfig_To_config_RegexpConfig is an autogenerated conversion function.
func Convert_v1alpha1_RegexpConfig_To_config_RegexpConfig(in *RegexpConfig, out *config.RegexpConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegexpConfig_To_config_RegexpConfig(in, out, s)
}

func autoConvert_config_RegexpConfig_To_v1alpha1_RegexpConfig(in *config.RegexpConfig, out *RegexpConfig, s conversion.Scope) error {
	out.CacheEnabled = (*bool)(unsafe.Pointer(in.CacheEnabled))
	out.CacheMaxNumEntries = in.CacheMaxNumEntries
	return nil
}

// Convert_config_RegexpConfig_To_v1alpha1_RegexpConfig is an autogenerated conversion function.
func Convert_config_RegexpConfig_To_v1alpha1_RegexpConfig(in *config.RegexpConfig, out *RegexpConfig, s conversion.Scope) error {
	return autoConvert_config_RegexpConfig_To_v1alpha1_RegexpConfig(in, out, s)
}

func autoConvert_v1alpha1_ResourceReference_To_config_ResourceReference(in *ResourceReference, out *config.ResourceReference, s conversion.Scope) error {
	if err := Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ResourceReference_To_config_ResourceReference is an autogenerated conversion function.
func Convert_v1alpha1_ResourceReference_To_config_ResourceReference(in *ResourceReference, out *config.ResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceReference_To_config_ResourceReference(in, out, s)
}

func autoConvert_config_ResourceReference_To_v1alpha1_ResourceReference(in *config.ResourceReference, out *ResourceReference, s conversion.Scope) error {
	if err := Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ResourceReference_To_v1alpha1_ResourceReference is an autogenerated conversion function.
func Convert_config_ResourceReference_To_v1alpha1_ResourceReference(in *config.ResourceReference, out *ResourceReference, s conversion.Scope) error {
	return autoConvert_config_ResourceReference_To_v1alpha1_ResourceReference(in, out, s)
}

func autoConvert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in *ResourceReferenceDetails, out *config.ResourceReferenceDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails is an autogenerated conversion function.
func Convert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in *ResourceReferenceDetails, out *config.ResourceReferenceDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceReferenceDetails_To_config_ResourceReferenceDetails(in, out, s)
}

func autoConvert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in *config.ResourceReferenceDetails, out *ResourceReferenceDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails is an autogenerated conversion function.
func Convert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in *config.ResourceReferenceDetails, out *ResourceReferenceDetails, s conversion.Scope) error {
	return autoConvert_config_ResourceReferenceDetails_To_v1alpha1_ResourceReferenceDetails(in, out, s)
}

func autoConvert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in *RetryOnFailureConfig, out *config.RetryOnFailureConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.InitialInterval = time.Duration(in.InitialInterval)
	out.MaxInterval = time.Duration(in.MaxInterval)
	out.MaxElapsedTime = time.Duration(in.MaxElapsedTime)
	out.Multiplier = in.Multiplier
	return nil
}

// Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig is an autogenerated conversion function.
func Convert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in *RetryOnFailureConfig, out *config.RetryOnFailureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RetryOnFailureConfig_To_config_RetryOnFailureConfig(in, out, s)
}

func autoConvert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in *config.RetryOnFailureConfig, out *RetryOnFailureConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.InitialInterval = time.Duration(in.InitialInterval)
	out.MaxInterval = time.Duration(in.MaxInterval)
	out.MaxElapsedTime = time.Duration(in.MaxElapsedTime)
	out.Multiplier = in.Multiplier
	return nil
}

// Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig is an autogenerated conversion function.
func Convert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in *config.RetryOnFailureConfig, out *RetryOnFailureConfig, s conversion.Scope) error {
	return autoConvert_config_RetryOnFailureConfig_To_v1alpha1_RetryOnFailureConfig(in, out, s)
}

func autoConvert_v1alpha1_SignalConfig_To_config_SignalConfig(in *SignalConfig, out *config.SignalConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Targets = *(*[]config.SignalTarget)(unsafe.Pointer(&in.Targets))
	return nil
}

// Convert_v1alpha1_SignalConfig_To_config_SignalConfig is an autogenerated conversion function.
func Convert_v1alpha1_SignalConfig_To_config_SignalConfig(in *SignalConfig, out *config.SignalConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SignalConfig_To_config_SignalConfig(in, out, s)
}

func autoConvert_config_SignalConfig_To_v1alpha1_SignalConfig(in *config.SignalConfig, out *SignalConfig, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Targets = *(*[]SignalTarget)(unsafe.Pointer(&in.Targets))
	return nil
}

// Convert_config_SignalConfig_To_v1alpha1_SignalConfig is an autogenerated conversion function.
func Convert_config_SignalConfig_To_v1alpha1_SignalConfig(in *config.SignalConfig, out *SignalConfig, s conversion.Scope) error {
	return autoConvert_config_SignalConfig_To_v1alpha1_SignalConfig(in, out, s)
}

func autoConvert_v1alpha1_SignalTarget_To_config_SignalTarget(in *SignalTarget, out *config.SignalTarget, s conversion.Scope) error {
	if err := Convert_v1alpha1_ExporterConfig_To_config_ExporterConfig(&in.Exporter, &out.Exporter, s); err != nil {
		return err
	}
	out.Filters = *(*[]config.FilterRule)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1alpha1_SignalTarget_To_config_SignalTarget is an autogenerated conversion function.
func Convert_v1alpha1_SignalTarget_To_config_SignalTarget(in *SignalTarget, out *config.SignalTarget, s conversion.Scope) error {
	return autoConvert_v1alpha1_SignalTarget_To_config_SignalTarget(in, out, s)
}

func autoConvert_config_SignalTarget_To_v1alpha1_SignalTarget(in *config.SignalTarget, out *SignalTarget, s conversion.Scope) error {
	if err := Convert_config_ExporterConfig_To_v1alpha1_ExporterConfig(&in.Exporter, &out.Exporter, s); err != nil {
		return err
	}
	out.Filters = *(*[]FilterRule)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_config_SignalTarget_To_v1alpha1_SignalTarget is an autogenerated conversion function.
func Convert_config_SignalTarget_To_v1alpha1_SignalTarget(in *config.SignalTarget, out *SignalTarget, s conversion.Scope) error {
	return autoConvert_config_SignalTarget_To_v1alpha1_SignalTarget(in, out, s)
}

func autoConvert_v1alpha1_SignalsConfig_To_config_SignalsConfig(in *SignalsConfig, out *config.SignalsConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_SignalConfig_To_config_SignalConfig(&in.Metrics, &out.Metrics, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SignalConfig_To_config_SignalConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SignalConfig_To_config_SignalConfig(&in.Traces, &out.Traces, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SignalConfig_To_config_SignalConfig(&in.Profiles, &out.Profiles, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SignalConfig_To_config_SignalConfig(&in.Events, &out.Events, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SignalsConfig_To_config_SignalsConfig is an autogenerated conversion function.
func Convert_v1alpha1_SignalsConfig_To_config_SignalsConfig(in *SignalsConfig, out *config.SignalsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SignalsConfig_To_config_SignalsConfig(in, out, s)
}

func autoConvert_config_SignalsConfig_To_v1alpha1_SignalsConfig(in *config.SignalsConfig, out *SignalsConfig, s conversion.Scope) error {
	if err := Convert_config_SignalConfig_To_v1alpha1_SignalConfig(&in.Metrics, &out.Metrics, s); err != nil {
		return err
	}
	if err := Convert_config_SignalConfig_To_v1alpha1_SignalConfig(&in.Logs, &out.Logs, s); err != nil {
		return err
	}
	if err := Convert_config_SignalConfig_To_v1alpha1_SignalConfig(&in.Traces, &out.Traces, s); err != nil {
		return err
	}
	if err := Convert_config_SignalConfig_To_v1alpha1_SignalConfig(&in.Profiles, &out.Profiles, s); err != nil {
		return err
	}
	if err := Convert_config_SignalConfig_To_v1alpha1_SignalConfig(&in.Events, &out.Events, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_SignalsConfig_To_v1alpha1_SignalsConfig is an autogenerated conversion function.
func Convert_config_SignalsConfig_To_v1alpha1_SignalsConfig(in *config.SignalsConfig, out *SignalsConfig, s conversion.Scope) error {
	return autoConvert_config_SignalsConfig_To_v1alpha1_SignalsConfig(in, out, s)
}

func autoConvert_v1alpha1_TLSConfig_To_config_TLSConfig(in *TLSConfig, out *config.TLSConfig, s conversion.Scope) error {
	out.InsecureSkipVerify = (*bool)(unsafe.Pointer(in.InsecureSkipVerify))
	out.CA = (*config.ResourceReference)(unsafe.Pointer(in.CA))
	out.Cert = (*config.ResourceReference)(unsafe.Pointer(in.Cert))
	out.Key = (*config.ResourceReference)(unsafe.Pointer(in.Key))
	out.ReloadInterval = time.Duration(in.ReloadInterval)
	return nil
}

// Convert_v1alpha1_TLSConfig_To_config_TLSConfig is an autogenerated conversion function.
func Convert_v1alpha1_TLSConfig_To_config_TLSConfig(in *TLSConfig, out *config.TLSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSConfig_To_config_TLSConfig(in, out, s)
}

func autoConvert_config_TLSConfig_To_v1alpha1_TLSConfig(in *config.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	out.InsecureSkipVerify = (*bool)(unsafe.Pointer(in.InsecureSkipVerify))
	out.CA = (*ResourceReference)(unsafe.Pointer(in.CA))
	out.Cert = (*ResourceReference)(unsafe.Pointer(in.Cert))
	out.Key = (*ResourceReference)(unsafe.Pointer(in.Key))
	out.ReloadInterval = time.Duration(in.ReloadInterval)
	return nil
}

// Convert_config_TLSConfig_To_v1alpha1_TLSConfig is an autogenerated conversion function.
func Convert_config_TLSConfig_To_v1alpha1_TLSConfig(in *config.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	return autoConvert_config_TLSConfig_To_v1alpha1_TLSConfig(in, out, s)
}
