//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfig) DeepCopyInto(out *CollectorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfig.
func (in *CollectorConfig) DeepCopy() *CollectorConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorConfigSpec) DeepCopyInto(out *CollectorConfigSpec) {
	*out = *in
	in.Signals.DeepCopyInto(&out.Signals)
	out.Logs = in.Logs
	out.Metrics = in.Metrics
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorConfigSpec.
func (in *CollectorConfigSpec) DeepCopy() *CollectorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorLogsConfig) DeepCopyInto(out *CollectorLogsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorLogsConfig.
func (in *CollectorLogsConfig) DeepCopy() *CollectorLogsConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorMetricsConfig) DeepCopyInto(out *CollectorMetricsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorMetricsConfig.
func (in *CollectorMetricsConfig) DeepCopy() *CollectorMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(CollectorMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextConditions) DeepCopyInto(out *ContextConditions) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextConditions.
func (in *ContextConditions) DeepCopy() *ContextConditions {
	if in == nil {
		return nil
	}
	out := new(ContextConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterConfig) DeepCopyInto(out *ExporterConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(ResourceReference)
		**out = **in
	}
	in.RetryOnFailure.DeepCopyInto(&out.RetryOnFailure)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterConfig.
func (in *ExporterConfig) DeepCopy() *ExporterConfig {
	if in == nil {
		return nil
	}
	out := new(ExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterAttribute) DeepCopyInto(out *FilterAttribute) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterAttribute.
func (in *FilterAttribute) DeepCopy() *FilterAttribute {
	if in == nil {
		return nil
	}
	out := new(FilterAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterRule) DeepCopyInto(out *FilterRule) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(LogFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricConditions != nil {
		in, out := &in.MetricConditions, &out.MetricConditions
		*out = make([]ContextConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogConditions != nil {
		in, out := &in.LogConditions, &out.LogConditions
		*out = make([]ContextConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ContextConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterRule.
func (in *FilterRule) DeepCopy() *FilterRule {
	if in == nil {
		return nil
	}
	out := new(FilterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogFilters) DeepCopyInto(out *LogFilters) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(LogMatchProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(LogMatchProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogRecord != nil {
		in, out := &in.LogRecord, &out.LogRecord
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogFilters.
func (in *LogFilters) DeepCopy() *LogFilters {
	if in == nil {
		return nil
	}
	out := new(LogFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogMatchProperties) DeepCopyInto(out *LogMatchProperties) {
	*out = *in
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make([]FilterAttribute, len(*in))
		copy(*out, *in)
	}
	if in.RecordAttributes != nil {
		in, out := &in.RecordAttributes, &out.RecordAttributes
		*out = make([]FilterAttribute, len(*in))
		copy(*out, *in)
	}
	if in.SeverityTexts != nil {
		in, out := &in.SeverityTexts, &out.SeverityTexts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SeverityNumber != nil {
		in, out := &in.SeverityNumber, &out.SeverityNumber
		*out = new(LogSeverityNumberMatchProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Bodies != nil {
		in, out := &in.Bodies, &out.Bodies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogMatchProperties.
func (in *LogMatchProperties) DeepCopy() *LogMatchProperties {
	if in == nil {
		return nil
	}
	out := new(LogMatchProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSeverityNumberMatchProperties) DeepCopyInto(out *LogSeverityNumberMatchProperties) {
	*out = *in
	if in.MatchUndefined != nil {
		in, out := &in.MatchUndefined, &out.MatchUndefined
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSeverityNumberMatchProperties.
func (in *LogSeverityNumberMatchProperties) DeepCopy() *LogSeverityNumberMatchProperties {
	if in == nil {
		return nil
	}
	out := new(LogSeverityNumberMatchProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricFilters) DeepCopyInto(out *MetricFilters) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(MetricMatchProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(MetricMatchProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataPoint != nil {
		in, out := &in.DataPoint, &out.DataPoint
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricFilters.
func (in *MetricFilters) DeepCopy() *MetricFilters {
	if in == nil {
		return nil
	}
	out := new(MetricFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricMatchProperties) DeepCopyInto(out *MetricMatchProperties) {
	*out = *in
	if in.Regexp != nil {
		in, out := &in.Regexp, &out.Regexp
		*out = new(RegexpConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricNames != nil {
		in, out := &in.MetricNames, &out.MetricNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make([]FilterAttribute, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricMatchProperties.
func (in *MetricMatchProperties) DeepCopy() *MetricMatchProperties {
	if in == nil {
		return nil
	}
	out := new(MetricMatchProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegexpConfig) DeepCopyInto(out *RegexpConfig) {
	*out = *in
	if in.CacheEnabled != nil {
		in, out := &in.CacheEnabled, &out.CacheEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegexpConfig.
func (in *RegexpConfig) DeepCopy() *RegexpConfig {
	if in == nil {
		return nil
	}
	out := new(RegexpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
	out.ResourceRef = in.ResourceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReferenceDetails) DeepCopyInto(out *ResourceReferenceDetails) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReferenceDetails.
func (in *ResourceReferenceDetails) DeepCopy() *ResourceReferenceDetails {
	if in == nil {
		return nil
	}
	out := new(ResourceReferenceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryOnFailureConfig) DeepCopyInto(out *RetryOnFailureConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryOnFailureConfig.
func (in *RetryOnFailureConfig) DeepCopy() *RetryOnFailureConfig {
	if in == nil {
		return nil
	}
	out := new(RetryOnFailureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalConfig) DeepCopyInto(out *SignalConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]SignalTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalConfig.
func (in *SignalConfig) DeepCopy() *SignalConfig {
	if in == nil {
		return nil
	}
	out := new(SignalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalTarget) DeepCopyInto(out *SignalTarget) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]FilterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalTarget.
func (in *SignalTarget) DeepCopy() *SignalTarget {
	if in == nil {
		return nil
	}
	out := new(SignalTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalsConfig) DeepCopyInto(out *SignalsConfig) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.Logs.DeepCopyInto(&out.Logs)
	in.Traces.DeepCopyInto(&out.Traces)
	in.Profiles.DeepCopyInto(&out.Profiles)
	in.Events.DeepCopyInto(&out.Events)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalsConfig.
func (in *SignalsConfig) DeepCopy() *SignalsConfig {
	if in == nil {
		return nil
	}
	out := new(SignalsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(ResourceReference)
		**out = **in
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(ResourceReference)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(ResourceReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
