---
apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-receiver-auth
  namespace: default
type: Opaque
stringData:
  bearertoken: "secret"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-receiver
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-receiver
  namespace: default
data:
  collector.yaml: |
    extensions:
      # Bearer token authentication extension
      bearertokenauth/server:
        tokens:
          - ${env:BEARER_TOKEN}

    receivers:
      otlp:
        protocols:
          http:
            include_metadata: true
            endpoint: 0.0.0.0:55690
            compression_algorithms: ["", "gzip"]
            # Enable authentication for HTTP endpoint
            auth:
              authenticator: bearertokenauth/server

    exporters:
      debug:
        verbosity: basic

    service:
      extensions:
        - bearertokenauth/server
      telemetry:
        logs:
          encoding: json
          level: info
        metrics:
          level: basic
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
      pipelines:
        metrics:
          exporters:
            - debug
          receivers:
            - otlp
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-receiver
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 55690
  selector:
    app.kubernetes.io/component: opentelemetry-receiver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-receiver
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-receiver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opentelemetry-receiver
    spec:
      containers:
      - args:
        - --config=/conf/collector.yaml
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: opentelemetry-receiver-auth
              key: bearertoken
        image: otel/opentelemetry-collector-contrib:0.141.0
        imagePullPolicy: IfNotPresent
        name: otc-container
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /conf
          name: otc-internal
        - mountPath: /etc/otel/auth
          name: auth-secret
          readOnly: true
      serviceAccountName: opentelemetry-receiver
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: collector.yaml
            path: collector.yaml
          name: opentelemetry-receiver
        name: otc-internal
      - name: auth-secret
        secret:
          secretName: opentelemetry-receiver-auth
          defaultMode: 0444
